require:
  - rubocop-openhab
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
  - 'scripts/**/*'

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
